# Server
spring.application.name=backend
server.port=8080
# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/senegal_tourism
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA and Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
# JWT
app.jwt.secret=S3n3g4lTourismS3cr3tK3yF0rJWTAuth2024!
app.jwt.access-token-expiration=900000
app.jwt.refresh-token-expiration=604800000
# Seed data
spring.sql.init.mode=never