spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

app.jwt.secret=${JWT_SECRET}
app.jwt.access-token-expiration=${APP_JWT_ACCESS_TOKEN_EXPIRATION}
app.jwt.refresh-token-expiration=${APP_JWT_REFRESH_TOKEN_EXPIRATION}